- name: exam
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:

    - name: Create exam container
      docker_container:
        name: php-apache-test
        state: started
        recreate: yes
        restart_policy: always
        image: bee7ch/webapp1:latest
        ports:
          - "80:80"